# 内容存储的位置
backend:
  name: git-gateway
  repo: joyarkdev/joyark-docs
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/images"
public_folder: "/images"

collections: # A list of collections the CMS should be able to edit
  - name: "fingertips" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Fingertips" # Used in the UI, ie.: "New Post"
    folder: "fingertips # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Body", name: "body", widget: "markdown"}
